name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore src/FT.sln
    - name: Build
      run: dotnet build  src/FT.sln --no-restore
    - name: Test
      run: dotnet test  src/FT.sln --no-build --verbosity normal
